# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only

name: Unit tests

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency:
    group: unit-tests-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
            -   name: Set up JDK 17
                uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Delete old comments
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                if: ${{ always() }}
                run: scripts/deleteOldComments.sh "test" "Unit" ${{github.event.number}}
            -   name: Run unit tests with coverage
                uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
                with:
                    arguments: jacocoTestGplayDebugUnitTest
            -   name: Upload failing results
                if: ${{ failure() }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: scripts/uploadReport.sh "${{ secrets.LOG_USERNAME }}" "${{ secrets.LOG_PASSWORD }}" ${{github.event.number}} "test" "Unit" ${{github.event.number}}
            -   name: Upload coverage to codecov
                uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: unit
                    fail_ci_if_error: true
            -   name: Upload jacoco artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
